config/routes.rb
Rails.application.routes.draw do
	resources :users
	get    'sign_in'   => 'sessions#new'
	post   'sign_in'   => 'sessions#create'
	delete 'sign_out'  => 'sessions#destroy'
	get 'movies/pagination/', to: 'sessions#pagination'
	get 'movies/:id', to: 'sessions#show'
	get 'search', to: 'sessions#search'
	root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true, length: {maximum: 50}
	validates :password, presence: true, length: {minimum: 6}
	validates :birthday, presence: true
	VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
	before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	include SessionsHelper
	def authorize
		unless logged_in?
			redirect_to root_url
		end
	end
	def correct_user?
		@user = User.find(params[:id])
		unless current_user == @user
			redirect_to users_path
		end
	end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	# Popular movies in the region of USA
	# Accept query ?region=pt-BR for set upcoming region
	Tmdb::Api.key( ENV['TMDB_API_KEY'] )
	def index
		@region = params[:id].nil? ? 'us' : params[:region]
		@popular = Tmdb::Movie.popular({region: 'us'})
	end
	
	# Return datas of the movies
	# (name, poster image, genre, overview and release date)
	# GET /movies/:ID
	def show
		@movie = Tmdb::Movie.detail(params[:id])
		@images = Tmdb::Movie.posters(params[:id])
	end

	# For use with infinite scroll
	# Idea: https://medium.com/wolox-driving-innovation/infinite-scrolling-ruby-on-rails-3fcd3bac0f75
	# GET /movies/pagination/?page=
	def pagination
		page = params[:page].nil? ? 1 : params[:page]
		region = params[:id].nil? ? 'us' : params[:region]
		popular = Tmdb::Movie.popular({page: page, region: region}).results
		render partial: 'users/movie', collection: popular, locals: {movie: popular}
	end

	# GET /search/:query
	def search
		@search = Tmdb::Search.movie(params[:query])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	#Tmdb::Api.key( ENV['TMDB_API_KEY'] )
	def create
		@region = params[:id].nil? ? 'us' : params[:region]
		@popular = Tmdb::Movie.popular({region: 'us'})
		#@popular = Tmdb::Movie.popular
		@user = User.find_by(email: params[:session][:email].downcase)
		if @user && @user.authenticate(params[:session][:password])
			#sign_in(@user)
			sign_in
			redirect_to current_user
		else
			render action: :new
		end
	end
	def destroy
		sign_out
		redirect_to root_url
	end
	def pagination
		page = params[:page].nil? ? 1 : params[:page]
		region = params[:id].nil? ? 'us' : params[:region]
		popular = Tmdb::Movie.popular({page: page, region: region}).results
		#popular = Tmdb::Movie.popular.results
		render partial: 'movie', collection: popular, locals: {movie: popular}
	end

	# GET /search/:query
	def search
		if params[:query].blank?
			redirect_to(root_path, alert: "Campo de pesquisa vazio!") and return
		else
			@search = Tmdb::Search.movie(params[:query])
		end
	end
	def show
		@movie = Tmdb::Movie.detail(params[:id])
		@images = Tmdb::Movie.posters(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, except: [:new, :create]
	before_action :correct_user?, only: [:edit, :update, :destroy]
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user, notice: "Usuário foi criado com sucesso!"
                        #tire o método de comentário quando criar o helper.
                        #Usuário depois de cadastrar-se acessa o sistema automaticamente
			#sign_in(@user)
		else
			render action: :new
		end
	end
	#def index
#		@users = User.all
#	end
#	def show
#		@user = User.find(params[:id])
#	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			render action: :edit
		end
	end
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		sign_out
		redirect_to root_path
	end
	private
		def user_params
			params.require(:user).permit(:name, :email, :birthday, :password, :password_confirmation)
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	# return names of the genre based on genre_id
	#Tmdb::Api.key( ENV['TMDB_API_KEY'] )
	def get_genre(genre_ids)
		return if genre_ids.empty? 
		genres = []

		genre_ids.each do |genre_id|
			# genres = Tmdb::Genre.movie_list.select{ |m| m.id == genre_id }.first[:name]
			genre_value = Tmdb::Resource.new("/genre/#{genre_id}").get
			genres << genre_value['name']
		end

		genres.join(', ').to_s
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in
		session[:user_id] = @user.id
	end
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	def block_access
		if current_user.present?
			redirect_to users_path
		end
	end
	def logged_in?
		!current_user.nil?
	end
	def sign_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
            <ul>
			  <li><%= link_to "Movies List", users_path %></li>          	
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li>
                <%= link_to "Log out", sign_out_path, method: "delete" %>
              </li>
			</ul>
				<%= form_tag(search_path, method: :get) do %>  
				      <%= search_field_tag :query, params[:query], placeholder: "Busca" %>  
					  <%= submit_tag ("Busca") %>				    
				<% end %>
		<% else %>
          <li><%= link_to "Log in", root_path %></li>        
		<% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
			<div class="field">
                        <%= f.label :birthday %>
                        <%= f.text_field :birthday %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/_movie.html.erb
<li class="movie-<%= movie.id %>">
	<a href="/users/<%= movie.id %>" title="<%= movie.original_title %>">
		<% if movie.poster_path %>
			<%= image_tag('https://image.tmdb.org/t/p/w300' + movie.poster_path, class: 'img-thumbnail') %>
		<% else %>
			<%= image_tag('https://dummyimage.com/300x450/000/fff', class: 'fallback-thumbnail') %>
		<% end %>
		<div class="movie-info">
			<h3 class="movie-title"><%= movie.title %></h3>
			<span class="movie-release">Release: <%= movie.release_date.to_date.strftime('%b, %m %Y') %></span>
			<span class="movie-genres">Genres: <%= get_genre(movie.genre_ids) %></span>
		</div>
	</a>
</li>

app/views/users/edit.html.erb
<h1>User Settings</h1>
<%= render 'form' %>
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
			<div class="field">
                        <%= f.label :birthday %>
                        <%= f.text_field :birthday %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
			<ul>
			            <li><%= link_to "Edit", edit_user_path(current_user) %></li>
			            <li><%= link_to "Delete", @user, method: :delete%></li>
			</ul>
<% end %>

app/views/users/index.html.erb
<% 	@popular = Tmdb::Movie.popular({region: 'us'}) %>
<h2>Filmes Populares - <%= @popular.total_results %> movies</h2>

<ul class="movies-list">
<% 	@popular = Tmdb::Movie.popular({region: 'us'}) %>
	<% @popular.results.each do |movie| %>
		<% if movie %>
			<%= render partial: 'users/movie', collection: movie, locals: {movie: movie} %>
		<% end %> 
	<% end %>
</ul>

app/views/users/list.html.erb
<h2>Filmes Populares - <%= @upcoming.total_results %> movies</h2>

<ul class="movies-list">
<% 	@popular = Tmdb::Movie.popular({region: 'us'}) %>
	<% @popular.results.each do |movie| %>
		<% if movie %>
			<%= render partial: 'users/movie', collection: movie, locals: {movie: movie} %>
		<% end %> 
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :name %>
                        <%= f.text_field :name %>
            </div>
			<div class="field">
                        <%= f.label :birthday %>
                        <%= f.text_field :birthday %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email %>
            </div>
            <div class="field">
                        <%= f.label :password %>
                        <%= f.password_field :password %>
            </div>
            <div class="field">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar"%>
            </div>
<% end %>

app/views/users/search.html.erb
<h3>Search Result</h3>

	<% @search.results.each do |movie| %>
		<% if movie %>
			<%= render partial: 'users/movie', collection: movie, locals: {movie: movie} %>
		<% end %> 
	<% end %>

app/views/users/show.html.erb
<html>
              <body>
                        
                          <% if current_user == @user %>
                                     <ul>
                                                 <li><%= link_to "Edit", edit_user_path(current_user) %></li>
                                                 <li><%= link_to "Delete", @user, method: :delete%></li>
                                     </ul>
									
									<ul class="movies-list">
										<% @popular.results.each do |movie| %>
											<% if movie %>
												<%= render partial: 'users/movie', collection: movie, locals: {movie: movie} %>
											<% end %> 
										<% end %>
									</ul>

									<span class="pagination" data-pagination-endpoint="/movies/pagination/" data-pagination-pages="<%= @popular.total_pages %>">
										Loading...
									</span>

                          <%end%>
              </body>
  </html>